### ISSUE TITLE
unittest hits a TypeError when running assertAlmostEqual

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#130]
I am now on the latest version of pylabrad and I am hitting a new error when I run some old test code.  It would be great if someone could run this code to confirm the error isn't some local configuration of mine.  I am trying to compare WithUnit values and trying to account for some small discrepancy  in WithUnit values.

```python
import unittest as ut
from unittest import TestLoader as _TL
from labrad.units import WithUnit


def test():
    suite = _TL().loadTestsFromTestCase(TestWithUnit)
    suites = [suite]
    alltests = ut.TestSuite(suites)
    ut.TextTestRunner(verbosity=0.).run(alltests)

class TestWithUnit(ut.TestCase):
    def test_almost_equal(self):
        expected_value =  WithUnit(9.15, 'ms')
        actual_value =  WithUnit(9.149999999999999, 'ms')
        self.assertAlmostEqual(expected_value, actual_value, 8)

    def test_equal(self):
        expected_value =  WithUnit(9.15, 'ms')
        actual_value =  WithUnit(9.15, 'ms')
        self.assertEqual(expected_value, actual_value)

test()
```

Gives the error:
```python

======================================================================
ERROR: test_almost_equal (__main__.TestWithUnit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-1-002141ccb048>", line 16, in test_almost_equal
    self.assertAlmostEqual(expected_value, actual_value, 8)
  File "C:\Python27\lib\unittest\case.py", line 556, in assertAlmostEqual
    if round(abs(second-first), places) == 0:
  File "C:\Python27\lib\site-packages\labrad\units.py", line 435, in __float__
    return self['']
  File "C:\Python27\lib\site-packages\labrad\units.py", line 380, in __getitem__
    factor, offset = self.unit.conversionTupleTo(unit)
  File "C:\Python27\lib\site-packages\labrad\util\cache.py", line 248, in wrapper
    return cache.get(key, user_function, *args, **kwds)
  File "C:\Python27\lib\site-packages\labrad\util\cache.py", line 166, in _get
    result = fn(*args, **kwds)
  File "C:\Python27\lib\site-packages\labrad\units.py", line 847, in conversionTupleTo
    raise TypeError("Incompatible units: '%s', '%s'" % (self, other))
TypeError: Incompatible units: 'ms', ''

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=1)
```

The actual_value in my real test case comes from code that is used to control equipment.  Perhaps this is expected based on changes to pylabrad code?

**Comment by chrismacklin** [comment]
I ran this using nose and reproduced this failure.

**Comment by jayich** [comment]
Great, thank you so much for this fix.
