### ISSUE TITLE
setup.py error on Windows

### ISSUE THREAD

**Issue by zchen088** [labrad/pylabrad#239]
When I do `run setup.py` in an IPython session, I get the following error:

```python
---------------------------------------------------------------------------
WindowsError                              Traceback (most recent call last)
C:\Users\Jimmy\Desktop\pylabrad\setup.py in <module>()
     50         'labrad.node': ['*.ini'],
     51     },
---> 52     scripts=[],
     53 )

C:\Python27\lib\distutils\core.pyc in setup(**attrs)
    109     # (ie. everything except distclass) to initialize it
    110     try:
--> 111         _setup_distribution = dist = klass(attrs)
    112     except DistutilsSetupError, msg:
    113         if 'name' in attrs:

C:\Python27\lib\site-packages\setuptools\dist.pyc in __init__(self, attrs)
    270         for ep in pkg_resources.iter_entry_points('distutils.setup_keywo
rds'):
    271             vars(self).setdefault(ep.name, None)
--> 272         _Distribution.__init__(self,attrs)
    273         if isinstance(self.metadata.version, numbers.Number):
    274             # Some people apparently take "version number" too literally
 :)

C:\Python27\lib\distutils\dist.pyc in __init__(self, attrs)
    285                     break
    286
--> 287         self.finalize_options()
    288
    289     def get_option_dict(self, command):

C:\Python27\lib\site-packages\setuptools\dist.pyc in finalize_options(self)
    325             if value is not None:
    326                 ep.require(installer=self.fetch_build_egg)
--> 327                 ep.load()(self, ep.name, value)
    328         if getattr(self, 'convert_2to3_doctests', None):
    329             # XXX may convert to set here when we can rely on set being
builtin

C:\Python27\lib\site-packages\setuptools_scm\integration.pyc in version_keyword(
dist, keyword, value)
     17     if getattr(value, '__call__', None):
     18         value = value()
---> 19     dist.metadata.version = get_version(**value)
     20
     21

C:\Python27\lib\site-packages\setuptools_scm\__init__.pyc in get_version(root, v
ersion_scheme, local_scheme, write_to, write_to_template, relative_to, parse)
    100     trace('root', repr(root))
    101
--> 102     version = _do_parse(root, parse)
    103
    104     if version:

C:\Python27\lib\site-packages\setuptools_scm\__init__.pyc in _do_parse(root, par
se)
     67     else:
     68         # include fallbacks after dropping them from the main entrypoint

---> 69         version = version_from_scm(root)
     70
     71     if version:

C:\Python27\lib\site-packages\setuptools_scm\__init__.pyc in version_from_scm(ro
ot)
     28
     29 def version_from_scm(root):
---> 30     return _version_from_entrypoint(root, 'setuptools_scm.parse_scm')
     31
     32

C:\Python27\lib\site-packages\setuptools_scm\__init__.pyc in _version_from_entry
point(root, entrypoint)
     34     ep = find_matching_entrypoint(root, entrypoint)
     35     if ep:
---> 36         return ep.load()(root)
     37
     38

C:\Python27\lib\site-packages\setuptools_scm\git.pyc in parse(root, describe_com
mand)
      9
     10 def parse(root, describe_command=DEFAULT_DESCRIBE):
---> 11     real_root, _, ret = do_ex('git rev-parse --show-toplevel', root)
     12     if ret:
     13         return

C:\Python27\lib\site-packages\setuptools_scm\utils.pyc in do_ex(cmd, cwd)
     56             LC_ALL='C',
     57             LANGUAGE='',
---> 58             HGPLAIN='1',
     59         ))
     60     )

C:\Python27\lib\subprocess.pyc in __init__(self, args, bufsize, executable, stdi
n, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, s
tartupinfo, creationflags)
    708                                 p2cread, p2cwrite,
    709                                 c2pread, c2pwrite,
--> 710                                 errread, errwrite)
    711         except Exception:
    712             # Preserve original exception in case os.close raises.

C:\Python27\lib\subprocess.pyc in _execute_child(self, args, executable, preexec
_fn, close_fds, cwd, env, universal_newlines, startupinfo, creationflags, shell,
 to_close, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite)
    956                                          env,
    957                                          cwd,
--> 958                                          startupinfo)
    959             except pywintypes.error, e:
    960                 # Translate pywintypes.error to WindowsError, which is

WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by maffoo** [comment]
I wouldn't expect this to work from inside IPython. What happens if you just run setup.py from the command line? Even better, use pip instead of running setup.py directly (e.g. `pip install .` from inside the pylabrad checkout if you want to install a dev version from source, or `pip install` to get the latest from PyPI).

**Comment by zchen088** [comment]
Tried `pip install .`, got a similar looking error:
```
C:\Users\Jimmy\Desktop\pylabrad>pip install .
Processing c:\users\jimmy\desktop\pylabrad
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\jimmy\appdata\local\temp\pip-ar0qnv-build\setup.py", line 5
2, in <module>
        scripts=[],
      File "c:\python27\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 272, in __in
it__
        _Distribution.__init__(self,attrs)
      File "c:\python27\lib\distutils\dist.py", line 287, in __init__
        self.finalize_options()
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 327, in fina
lize_options
        ep.load()(self, ep.name, value)
      File "c:\python27\lib\site-packages\setuptools_scm\integration.py", line 1
9, in version_keyword
        dist.metadata.version = get_version(**value)
      File "c:\python27\lib\site-packages\setuptools_scm\__init__.py", line 102,
 in get_version
        version = _do_parse(root, parse)
      File "c:\python27\lib\site-packages\setuptools_scm\__init__.py", line 69,
in _do_parse
        version = version_from_scm(root)
      File "c:\python27\lib\site-packages\setuptools_scm\__init__.py", line 30,
in version_from_scm
        return _version_from_entrypoint(root, 'setuptools_scm.parse_scm')
      File "c:\python27\lib\site-packages\setuptools_scm\__init__.py", line 36,
in _version_from_entrypoint
        return ep.load()(root)
      File "c:\python27\lib\site-packages\setuptools_scm\git.py", line 11, in pa
rse
        real_root, _, ret = do_ex('git rev-parse --show-toplevel', root)
      File "c:\python27\lib\site-packages\setuptools_scm\utils.py", line 58, in
do_ex
        HGPLAIN='1',
      File "c:\python27\lib\subprocess.py", line 710, in __init__
        errread, errwrite)
      File "c:\python27\lib\subprocess.py", line 958, in _execute_child
        startupinfo)
    WindowsError: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\jimmy\ap
pdata\local\temp\pip-ar0qnv-build\
```

**Comment by maffoo** [comment]
So, it looks like it's failing to find a git executable. I guess this is a problem with the `setuptools_scm` module, which we're using to do versioning. As a short-term workaround you might try commenting out the `use_scm_version` arg to setup [here](https://github.com/labrad/pylabrad/blob/master/setup.py#L41). It's possible the unmodified setup.py will work if you run itfrom the git bash shell, or if you install git for windows in the mode where it puts git on the path for the regular command shell although I haven't tried that latter installation mode.

**Comment by zchen088** [comment]
Running from git bash seems to work. Thanks!
