### ISSUE TITLE
Data Vault is not working after updating pylabrad

### ISSUE THREAD

**Issue by zibrov-zlobin** [labrad/pylabrad#250]
After updating pylabrad to 0.95.3 Data Vault started to fail opening datasets(ver 2.3.4)
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Laughlin\Anaconda2\lib\site-packages\labrad\client.py", line 67
, in __call__
    return f.result() if wait else f
  File "C:\Users\Laughlin\Anaconda2\lib\site-packages\labrad\concurrent.py", lin
e 100, in result
    self._result = super(MutableFuture, self).result(timeout)
  File "C:\Users\Laughlin\Anaconda2\lib\site-packages\concurrent\futures\_base.p
y", line 405, in result
    return self.__get_result()
  File "C:\Users\Laughlin\Anaconda2\lib\site-packages\concurrent\futures\_base.p
y", line 357, in __get_result
    raise type(self._exception), self._exception, self._traceback
labrad.types.Error: (0) [Data Vault] Remote Traceback (most recent call last):
  File "C:\Users\Laughlin\Anaconda2\lib\site-packages\labrad\server.py", line 23
2, in request_handler
    result = yield setting.handleRequest(self, c.data, flat_data)
  File "C:\Users\Laughlin\Anaconda2\lib\site-packages\labrad\decorators.py", lin
e 181, in handleRequest
    return self.func(server, c, data)
  File "c:\scalabrad-0.5.0\servers\datavault\server.py", line 182, in open
    dataset = session.openDataset(name)
  File "c:\scalabrad-0.5.0\servers\datavault\__init__.py", line 268, in openData
set
    dataset = Dataset(self, name)
  File "c:\scalabrad-0.5.0\servers\datavault\__init__.py", line 340, in __init__

    self.access()
  File "c:\scalabrad-0.5.0\servers\datavault\__init__.py", line 453, in access
    self.save()
  File "c:\scalabrad-0.5.0\servers\datavault\__init__.py", line 436, in save
    data_bytes, t = T.flatten(par['data'])
exceptions.ValueError: too many values to unpack
 [payload=None]
```

**Comment by maffoo** [comment]
There's a PR open to fix this in the data vault: martinisgroup/servers#343. For now, I'd suggest downgrading pylabrad to version 0.95.1.
