### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by nrdlove** [labrad/pylabrad#276]
Did anyone encount the problem like this:

First, I run the LabRAD v1.1.3 and then run the following command on python

import labrad
cnx = labrad.connect()

However, this is not success and I get an Exception Traceback like this:

Traceback (most recent call last):
 File "C:\Python27\lib\site-packages\labrad\__init__.py", line 24, in connect
    cxn = backend.connect(host=host, port=port, name=name, **kw)
  File "C:\Python27\lib\site-packages\labrad\backend.py", line 418, in connect
    cxn.connect(host, port, **kw)
  File "C:\Python27\lib\site-packages\labrad\backend.py", line 45, in connect
    username=username, headless=headless)
  File "C:\Python27\lib\site-packages\labrad\backend.py", line 108, in _connect
    self.cxn = self.call(_connect_deferred).result()
  File "C:\Python27\lib\site-packages\concurrent\futures\_base.py", line 405, in result
    return self.__get_result()
  File "C:\Python27\lib\site-packages\concurrent\futures\_base.py", line 357, in __get_result
    raise type(self._exception), self._exception, self._traceback
Exception: Connection lost.

**Comment by maffoo** [comment]
Not sure what the problem could be here, but we're not developing the old delphi manager anymore, so it would be much better if you can upgrade to [scalabrad](https://github.com/labrad/scalabrad).

**Comment by nrdlove** [comment]
OK! It works quite well by using scalabrad. Thanks a lot.

**Comment by pppplin** [comment]
hi I just encountered the exact same problem, I'm in Windows7, did you figure out the problem with pylabrad? Many thanks.
